name: Generate hosts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do generating
        run: |
          ./generate-hosts.sh >.hosts
          if [ ! -s .hosts ] || cmp -s .hosts hosts; then
            rm .hosts
            exit
          fi
          mv .hosts hosts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate hosts"
          git push
