name: Generate hosts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate
        id: generate
        run: |
          d=$(date -u)
          ./generate-hosts.sh >hosts
          [ -z "$(git status -s)" ] && exit
          echo "DATE=$d" >>"$GITHUB_OUTPUT"

      - name: Update
        if: ${{ steps.generate.outputs.DATE != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.generate.outputs.DATE }}
