name: Generate hosts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Do generating
        run: |
          content=$(./generate-hosts.sh)
          [ -n "$content" ] && echo "$content" >hosts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generate hosts"
          git push
